import { handleTokenSettings, readTokenSettings } from './settings.js';
const BASE58='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';
const PUMP='6EF8rrecthR5Dkzon8Nwu78hRvfCKubJ14M5uBEwF6P';
const PUMP_SWAP='pAMMBay6oceH9fJKBRHGP5D4bD4sWpmSwMn52FMfXEA';
const DISC=[189,219,127,211,78,230,97,238];
const memo=new Map();
export function base58(bytes){let n=0n;for(const b of bytes)n=n*256n+BigInt(b);let s='';while(n){s=BASE58[Number(n%58n)]+s;n/=58n}for(const b of bytes){if(b!==0)break;s='1'+s}return s}
export function parseTrades(tx,mint,signature){if(!tx?.meta||tx.meta.err)return[];let stack=[],events=[],index=0;for(const log of tx.meta.logMessages||[]){const invoke=log.match(/^Program (\w+) invoke/);if(invoke){stack.push(invoke[1]);continue}if(/^Program \w+ (success|failed)/.test(log)){stack.pop();continue}if(stack.at(-1)!==PUMP||!log.startsWith('Program data: '))continue;let bytes;try{bytes=Uint8Array.from(atob(log.slice(14)),c=>c.charCodeAt(0))}catch{continue}if(bytes.length<97||!DISC.every((b,i)=>bytes[i]===b)||base58(bytes.slice(8,40))!==mint)continue;const v=new DataView(bytes.buffer),sol=Number(v.getBigUint64(40,true))/1e9,tokens=Number(v.getBigUint64(48,true))/1e6;if(!Number.isFinite(sol)||sol<=0||tokens<=0)continue;events.push({id:signature+':'+index++,signature,type:bytes[56]?'buy':'sell',solAmount:sol,price:sol/tokens,timestamp:Number(v.getBigInt64(89,true))*1000,demo:false})}if(events.length)return events;
// PumpSwap trades may not emit the bonding-curve event. Use signer token
// balance changes only for transactions invoking the official swap program.
if(!(tx.meta.logMessages||[]).some(l=>l.startsWith('Program '+PUMP_SWAP+' invoke')))return[];const signer=tx.transaction?.message?.accountKeys?.find(k=>k.signer);const owner=typeof signer==='string'?signer:signer?.pubkey;if(!owner)return[];const amount=balances=>(balances||[]).filter(b=>b.mint===mint&&b.owner===owner).reduce((s,b)=>s+Number(b.uiTokenAmount.uiAmountString),0);const delta=amount(tx.meta.postTokenBalances)-amount(tx.meta.preTokenBalances);const account=tx.transaction.message.accountKeys.findIndex(k=>(typeof k==='string'?k:k.pubkey)===owner);const solDelta=(tx.meta.postBalances[account]-tx.meta.preBalances[account]+tx.meta.fee)/1e9;if(!delta||!solDelta||Math.sign(delta)===Math.sign(solDelta))return[];return[{id:signature+':swap',signature,type:delta>0?'buy':'sell',solAmount:Math.abs(solDelta),price:Math.abs(solDelta/delta),timestamp:(tx.blockTime||Date.now()/1000)*1000,demo:false,estimated:true}]}
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json','Cache-Control':'no-store'}});
async function rpc(env,method,params){const endpoint=env.SOLANA_RPC_URL||'https://api.mainnet-beta.solana.com';const res=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params}),signal:AbortSignal.timeout(12000)});if(!res.ok)throw Error(res.status===429?'Solana feed rate-limited. Add a dedicated RPC endpoint in site settings.':'Solana feed unavailable ('+res.status+').');const body=await res.json();if(body.error)throw Error('Solana RPC: '+body.error.message);return body.result}
export async function handleApi(request,env){const url=new URL(request.url);if(url.pathname==='/api/config')return handleTokenSettings(request,env);if(request.method!=='GET')return json({error:'Method not allowed.'},405);if(url.pathname==='/api/status')return json({websocket:!!env.PUMPPORTAL_API_KEY,rpc:!!env.SOLANA_RPC_URL});if(!['/api/trades','/api/live'].includes(url.pathname))return json({error:'Not found'},404);const mint=url.searchParams.get('mint')||'';if(!/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(mint))return json({error:'Invalid token address.'},400);let settings;try{settings=await readTokenSettings(env)}catch{return json({error:'Token settings unavailable.'},503)}if(!settings?.mint)return json({error:'The owner has not connected a token yet.'},409);if(mint!==settings.mint)return json({error:'Only the owner-configured token can be viewed.'},403);
if(url.pathname==='/api/live'){if(!env.PUMPPORTAL_API_KEY)return json({error:'Streaming feed is not configured.'},503);if(request.headers.get('Upgrade')?.toLowerCase()!=='websocket')return json({error:'WebSocket connection required.'},426);const pair=new WebSocketPair(),client=pair[0],server=pair[1];server.accept();const upstream=new WebSocket('wss://pumpportal.fun/api/data?api-key='+encodeURIComponent(env.PUMPPORTAL_API_KEY));upstream.addEventListener('open',()=>upstream.send(JSON.stringify({method:'subscribeTokenTrade',keys:[mint]})));upstream.addEventListener('message',e=>{try{const event=JSON.parse(e.data);if(event.mint!==mint||!['buy','sell'].includes(event.txType)||!event.signature)return;const sol=Number(event.solAmount),tokens=Number(event.tokenAmount);if(sol<=0||tokens<=0)return;server.send(JSON.stringify({id:event.signature,signature:event.signature,type:event.txType,solAmount:sol,price:sol/tokens,timestamp:Date.now(),demo:false}))}catch{}});const close=()=>{try{upstream.close()}catch{}try{server.close()}catch{}};upstream.addEventListener('error',close);upstream.addEventListener('close',close);server.addEventListener('close',close);server.addEventListener('error',close);return new Response(null,{status:101,webSocket:client})}
const cursor=url.searchParams.get('cursor');if(cursor&&!/^[1-9A-HJ-NP-Za-km-z]{64,90}$/.test(cursor))return json({error:'Invalid feed cursor.'},400);const key=mint+':'+(cursor||'');const cached=memo.get(key);if(cached&&Date.now()-cached.time<6500)return json(cached.data);try{if(!cursor){const mintInfo=await rpc(env,'getAccountInfo',[mint,{encoding:'base64',commitment:'confirmed'}]);if(!mintInfo?.value)return json({error:'Token not found on Solana mainnet. Check the CA after launch.'},404);const latest=await rpc(env,'getSignaturesForAddress',[mint,{limit:1,commitment:'confirmed'}]);return json({cursor:latest?.[0]?.signature||null,trades:[],warning:'Synced · waiting for new trades'})}
let signatures=[],before;for(let page=0;page<4;page++){const result=await rpc(env,'getSignaturesForAddress',[mint,{limit:100,until:cursor,...(before?{before}:{}),commitment:'confirmed'}]);signatures.push(...result);if(result.length<100)break;before=result.at(-1).signature}let warning=signatures.length===400?'High activity · RPC history window reached. Configure the streaming feed for full coverage.':null;const pending=signatures.reverse().slice(0,12);const trades=[];let next=cursor;for(const info of pending){if(info.err){next=info.signature;continue}const tx=await rpc(env,'getTransaction',[info.signature,{encoding:'jsonParsed',maxSupportedTransactionVersion:0,commitment:'confirmed'}]);if(!tx)break;trades.push(...parseTrades(tx,mint,info.signature));next=info.signature}if(signatures.length>12)warning='Catching up · '+(signatures.length-12)+' transactions queued';const data={cursor:next,trades,warning};memo.set(key,{time:Date.now(),data});if(memo.size>100)memo.delete(memo.keys().next().value);return json(data)}catch(e){return json({error:e.message||'Trade feed unavailable.'},503)}}
