import * as THREE from 'three';
import {OrbitControls} from './vendor/OrbitControls.js';
const $=id=>document.getElementById(id);
const state={mode:'loading',mint:'',paused:false,chaos:18,kills:0,trades:0,price:3.2e-8,events:[],history:[3.2e-8],seen:new Set(),cursor:null,generation:0,auto:true,socket:null};
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
let audio;
function tone(freq=240){if(!$('sound-toggle').checked)return;try{audio??=new AudioContext();audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.type='triangle';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq/3,audio.currentTime+.12);g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.15);o.connect(g);g.connect(audio.destination);o.start();o.stop(audio.currentTime+.16)}catch{}}
function registerTrade(e){if(state.seen.has(e.id))return;state.seen.add(e.id);if(state.seen.size>2000)state.seen.delete(state.seen.values().next().value);state.trades++;const amount=Number(e.solAmount)||0;state.chaos=clamp(state.chaos+(e.type==='buy'?8:4)+Math.min(12,Math.log1p(amount)*4),0,100);if(Number.isFinite(e.price)&&e.price>0){state.price=e.price;state.history.push(e.price);if(state.history.length>100)state.history.shift()}state.events.unshift(e);state.events=state.events.slice(0,30);renderFeed();updateTelemetry();drawChart();tone(e.type==='buy'?500:180)}
function demoTrade(type){if(state.mode!=='demo')return;const amount=Math.round((.06+Math.random()*2)*100)/100;const price=state.price*(type==='buy'?1.02+Math.random()*.12:.94-Math.random()*.08);registerTrade({id:'demo-'+Date.now()+'-'+Math.random(),type,solAmount:amount,price,timestamp:Date.now(),demo:true})}
function renderFeed(){const list=$('feed-list');list.replaceChildren();for(const e of state.events){const row=document.createElement('div');row.className='feed-row '+(e.type==='sell'?'sell-event':'');const side=document.createElement('span');side.textContent=e.type.toUpperCase();const value=document.createElement('strong');value.textContent=Number(e.solAmount).toFixed(3)+' SOL';const sub=document.createElement('small');sub.textContent=e.demo?'SIMULATED':e.id.slice(0,6)+'…'+e.id.slice(-4);value.append(sub);const time=document.createElement('span');time.textContent=new Date(e.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'});row.append(side,value,time);list.append(row)}if(!state.events.length){const p=document.createElement('p');p.className='feed-empty';p.textContent='Waiting for the first event.';list.append(p)}$('trade-count').textContent=state.trades+' EVENTS'}
function updateTelemetry(){const n=Math.round(state.chaos);let level=n<30?'STALKER':n<55?'HUNTER':n<80?'BERSERKER':'FRENZY';let color=n<55?'#c7ef77':n<80?'#edc76b':'#f28b68';$('aggression').textContent=n;$('aggression').style.color=color;$('level-name').textContent=level;$('level-name').style.color=color;$('aggression-fill').style.width=n+'%';$('aggression-fill').style.background=color;$('behavior-description').textContent=n<30?'Patient stalking. Precision strikes.':n<55?'Faster pursuit. Relentless strikes.':n<80?'Rapid attacks. The field is erupting.':'Overdrive. No prey is safe.';$('acquisition').textContent=(1+n/40).toFixed(1)+'×';$('intensity').textContent=(1+n/28).toFixed(1)+'×';$('pressure').textContent=n<30?'Low':n<65?'Elevated':'Critical';$('kills').textContent=state.kills;$('strike-rate').textContent=(1/(1.4/(1+n/28))).toFixed(1);$('speed').textContent=(1.2+n*.04).toFixed(1);$('price').textContent=state.mode==='live'&&state.trades===0?'Waiting for trade':state.price.toFixed(11)}
function canvasContext(id){const c=$(id),r=c.getBoundingClientRect(),d=Math.min(devicePixelRatio,2);if(c.width!==Math.round(r.width*d)||c.height!==Math.round(r.height*d)){c.width=Math.round(r.width*d);c.height=Math.round(r.height*d)}const ctx=c.getContext('2d');ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,r.width,r.height);return{ctx,w:r.width,h:r.height}}
function drawChart(){const{ctx,w,h}=canvasContext('chart');ctx.strokeStyle='#1e2b21';ctx.lineWidth=1;for(let y=12;y<h;y+=25){ctx.beginPath();ctx.moveTo(18,y);ctx.lineTo(w-18,y);ctx.stroke()}if(state.mode==='live'&&!state.history.length){ctx.fillStyle='#6a826f';ctx.font='11px monospace';ctx.fillText('Waiting for confirmed trades',18,h/2);return}const data=state.history.length>1?state.history:[state.price,state.price];const lo=Math.min(...data)*.98,hi=Math.max(...data)*1.02;const pts=data.map((p,i)=>[18+i*(w-36)/(data.length-1),h-10-(p-lo)/(hi-lo)*(h-25)]);const grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#c7ef772b');grad.addColorStop(1,'#c7ef7700');ctx.beginPath();ctx.moveTo(pts[0][0],h);for(const[x,y]of pts)ctx.lineTo(x,y);ctx.lineTo(pts.at(-1)[0],h);ctx.closePath();ctx.fillStyle=grad;ctx.fill();ctx.beginPath();for(let i=0;i<pts.length;i++){const[x,y]=pts[i];i?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.strokeStyle='#bde97b';ctx.lineWidth=1.6;ctx.stroke();const[x,y]=pts.at(-1);ctx.fillStyle='#d6f99c';ctx.beginPath();ctx.arc(x,y,3,0,Math.PI*2);ctx.fill()}
function setFeedStatus(text){$('feed-status').textContent=text}
function resetSession(){state.chaos=18;state.kills=0;state.trades=0;state.events=[];state.history=[3.2e-8];state.price=3.2e-8;state.seen.clear();state.cursor=null;renderFeed();updateTelemetry();drawChart()}
function enterDemo(){state.generation++;state.socket?.close();state.socket=null;state.mode='demo';state.mint='';resetSession();$('mode-pill').textContent='DEMO FEED';$('token-label').textContent='Token not launched';$('footer-mode').textContent='DEMO MODE · NO TOKEN CONNECTED';$('chart-kind').textContent='SIMULATED TRADES';$('chart-unit').textContent='DEMO PRICE · SOL / TOKEN';$('demo-panel').hidden=false;$('token-link').href='https://www.pump.fun';setFeedStatus('Demo events · not blockchain trades');}
function validMint(input){let text=input.trim();if(/^https?:\/\//.test(text)){try{const u=new URL(text);if(!['pump.fun','www.pump.fun'].includes(u.hostname))return null;text=u.pathname.split('/').filter(Boolean).at(-1)||''}catch{return null}}if(!/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(text))return null;const alphabet='123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz';let n=0n;for(const c of text)n=n*58n+BigInt(alphabet.indexOf(c));let bytes=0;for(;n>0n;n>>=8n)bytes++;for(const c of text){if(c==='1')bytes++;else break}return bytes===32?text:null}
async function startFeed(generation){
  let status;try{status=await fetch('/api/status').then(r=>r.json())}catch{}
  if(generation!==state.generation)return;
  if(!status?.websocket){pollFeed(generation);return}
  const endpoint=new URL('/api/live',location.href);endpoint.protocol=location.protocol==='https:'?'wss:':'ws:';endpoint.searchParams.set('mint',state.mint);
  const ws=new WebSocket(endpoint);state.socket=ws;
  ws.onopen=()=>{if(generation!==state.generation){ws.close();return}$('mode-pill').textContent='LIVE STREAM';setFeedStatus('Streaming · waiting for new trades');$('footer-mode').textContent='LIVE STREAM · '+state.mint.slice(0,6)+'…'+state.mint.slice(-4)};
  ws.onmessage=e=>{if(generation!==state.generation)return;try{const trade=JSON.parse(e.data);if(trade.feedError){setFeedStatus(trade.feedError);return}if(['buy','sell'].includes(trade.type)&&trade.id){registerTrade(trade);setFeedStatus('Streaming · real-time token trades')}}catch{}};
  ws.onclose=()=>{if(generation!==state.generation||state.mode!=='live')return;$('mode-pill').textContent='FEED OFFLINE';setFeedStatus('Stream disconnected · retrying');$('footer-mode').textContent='LIVE STREAM OFFLINE · DEMO EVENTS DISABLED';setTimeout(()=>startFeed(generation),8000)};
  ws.onerror=()=>ws.close();
}
async function pollFeed(generation){if(generation!==state.generation||state.mode!=='live')return;try{const q=new URLSearchParams({mint:state.mint});if(state.cursor)q.set('cursor',state.cursor);const res=await fetch('/api/trades?'+q,{signal:AbortSignal.timeout(25000)});const data=await res.json();if(generation!==state.generation)return;if(!res.ok)throw new Error(data.error||'Feed unavailable');if(data.cursor)state.cursor=data.cursor;for(const trade of data.trades||[])registerTrade(trade);setFeedStatus(data.warning||'Connected · confirmed Solana trades');$('mode-pill').textContent='LIVE FEED';$('footer-mode').textContent='LIVE MODE · '+state.mint.slice(0,6)+'…'+state.mint.slice(-4);$('token-help').textContent=data.warning||'The site owner sets the token for all viewers.'}catch(e){if(generation!==state.generation)return;setFeedStatus('Feed unavailable · retrying');$('mode-pill').textContent='FEED OFFLINE';$('token-help').textContent=e.message==='The operation was aborted due to timeout'?'Feed timed out. Retrying shortly.':e.message;$('footer-mode').textContent='LIVE FEED OFFLINE · DEMO EVENTS DISABLED'}if(generation===state.generation)setTimeout(()=>pollFeed(generation),7000)}
function connectMint(mint){state.generation++;state.socket?.close();state.socket=null;state.mode='live';state.mint=mint;resetSession();state.history=[];drawChart();$('mode-pill').textContent='CONNECTING';$('token-label').textContent=mint.slice(0,6)+'…'+mint.slice(-4);$('footer-mode').textContent='CONNECTING TO SOLANA';$('chart-kind').textContent='CONFIRMED TRADES';$('chart-unit').textContent='LAST TRADE · SOL / TOKEN';$('price').textContent='Waiting for trade';$('demo-panel').hidden=true;$('token-link').href='https://pump.fun/coin/'+mint;setFeedStatus('Connecting · syncing to current activity');startFeed(state.generation)}
$('demo-buy').onclick=()=>demoTrade('buy');$('demo-sell').onclick=()=>demoTrade('sell');$('auto-demo').onchange=e=>state.auto=e.target.checked;setInterval(()=>{if(state.mode==='demo'&&state.auto&&!state.paused)demoTrade(Math.random()<.72?'buy':'sell')},5200);
let world;
try{world=initWorld()}catch(e){$('scene-loading').textContent='3D rendering could not start. Enable WebGL and reload.';console.error(e)}
function initWorld(){const container=$('viewer');const scene=new THREE.Scene();scene.background=new THREE.Color('#070c09');scene.fog=new THREE.FogExp2('#070c09',.019);const camera=new THREE.PerspectiveCamera(42,1,.1,120);camera.position.set(9,7,11);const renderer=new THREE.WebGLRenderer({antialias:true,alpha:false});renderer.setPixelRatio(Math.min(devicePixelRatio,1.75));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.setClearColor('#070c09');container.append(renderer.domElement);renderer.domElement.setAttribute('aria-label','Interactive 3D mantis battlefield');renderer.domElement.setAttribute('role','img');const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,1,0);controls.enableDamping=true;controls.dampingFactor=.06;controls.minDistance=6;controls.maxDistance=32;controls.maxPolarAngle=Math.PI/2-.03;controls.autoRotateSpeed=.25;const resize=()=>{const w=container.clientWidth,h=container.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix()};new ResizeObserver(resize).observe(container);resize();scene.add(new THREE.HemisphereLight('#e7ffd6','#203b26',2.2));const light=new THREE.DirectionalLight('#c6f5a3',3);light.position.set(5,9,5);scene.add(light);const back=new THREE.DirectionalLight('#3eeaa5',2);back.position.set(-4,3,-4);scene.add(back);
const grid=new THREE.GridHelper(36,36,'#38462b','#17291e');grid.position.y=-.03;scene.add(grid);const floor=new THREE.Mesh(new THREE.PlaneGeometry(36,36),new THREE.MeshStandardMaterial({color:'#09120d',roughness:1,transparent:true,opacity:.6}));floor.rotation.x=-Math.PI/2;floor.position.y=-.08;scene.add(floor);const ring=new THREE.Mesh(new THREE.RingGeometry(7.7,7.73,100),new THREE.MeshBasicMaterial({color:'#395837',side:THREE.DoubleSide,transparent:true,opacity:.6}));ring.rotation.x=-Math.PI/2;ring.position.y=.01;scene.add(ring);
const bodies=[],wires=[];const mantis=new THREE.Group();const limeMat=new THREE.MeshStandardMaterial({color:'#728f36',roughness:.4,metalness:.25,transparent:true,opacity:.9,emissive:'#294919',emissiveIntensity:.32});const wireMat=new THREE.LineBasicMaterial({color:'#b8d86b',transparent:true,opacity:.33});
function mesh(g,geo,mat=limeMat,wire=true){const m=new THREE.Mesh(geo,mat);g.add(m);if(mat===limeMat)bodies.push(m);if(wire){const lines=new THREE.LineSegments(new THREE.WireframeGeometry(geo),wireMat);m.add(lines);wires.push(lines)}return m}
function orb(g,p,s,mat=limeMat){const m=mesh(g,new THREE.SphereGeometry(1,12,8),mat);m.position.set(...p);m.scale.set(...s);return m}
function limb(g,a,b,r1=.08,r2=.05,mat=limeMat){const from=new THREE.Vector3(...a),to=new THREE.Vector3(...b),v=to.clone().sub(from);const m=mesh(g,new THREE.CylinderGeometry(r2,r1,v.length(),8,1),mat);m.position.copy(from).add(to).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),v.normalize());return m}
const abdomen=orb(mantis,[0,1.5,-.8],[.48,.36,1.25]);for(let i=0;i<6;i++){const seg=orb(mantis,[0,1.52,-1.6+i*.25],[.49-i*.025,.29,.07]);seg.material=limeMat}limb(mantis,[0,1.65,-.05],[0,2.75,.8],.12,.15);orb(mantis,[0,2.74,.8],[.21,.15,.2]);
const head=new THREE.Group();head.position.set(0,2.92,.98);mantis.add(head);const headGeo=new THREE.BufferGeometry();const points=[-.57,.2,.04,.57,.2,.04,0,-.23,.2,0,.16,-.27];const faces=[0,1,2,0,3,1,0,2,3,1,3,2];headGeo.setAttribute('position',new THREE.Float32BufferAttribute(faces.flatMap(i=>points.slice(i*3,i*3+3)),3));headGeo.computeVertexNormals();mesh(head,headGeo);const eyeMat=new THREE.MeshStandardMaterial({color:'#d2e98d',roughness:.25,emissive:'#769448',emissiveIntensity:.45});orb(head,[-.48,.19,.065],[.2,.21,.22],eyeMat);orb(head,[.48,.19,.065],[.2,.21,.22],eyeMat);const pupil=new THREE.MeshBasicMaterial({color:'#182914'});orb(head,[-.49,.18,.265],[.06,.08,.04],pupil);orb(head,[.49,.18,.265],[.06,.08,.04],pupil);for(const s of[-1,1]){limb(head,[s*.24,.27,0],[s*.4,.75,.13],.018,.008);limb(head,[s*.4,.75,.13],[s*.76,1.17,.38],.008,.004)}
const arms=[];for(const s of[-1,1]){const arm=new THREE.Group();arm.position.set(s*.17,2.5,.65);mantis.add(arm);limb(arm,[0,0,0],[s*.58,-.43,.55],.1,.075);orb(arm,[s*.58,-.43,.55],[.1,.1,.1]);limb(arm,[s*.58,-.43,.55],[s*.4,.1,1.03],.13,.06);limb(arm,[s*.4,.1,1.03],[s*.29,-.5,.66],.06,.025);for(let i=0;i<6;i++){const y=-.38+i*.073,z=.57+i*.064;limb(arm,[s*(.58-i*.022),y,z],[s*(.38-i*.02),y-.04,z+.02],.025,.002)}arms.push(arm)}
const legs=[];for(const s of[-1,1])for(let i=0;i<2;i++){const g=new THREE.Group();g.position.set(s*.23,1.45,-.3-i*.9);mantis.add(g);limb(g,[0,0,0],[s*.85,-.35,.2-i*.2],.065,.045);limb(g,[s*.85,-.35,.2-i*.2],[s*1.38,-1.37,.55-i*.55],.045,.018);limb(g,[s*1.38,-1.37,.55-i*.55],[s*1.53,-1.42,.76-i*.55],.018,.01);legs.push(g)}
const wingMat=new THREE.MeshStandardMaterial({color:'#88aa44',transparent:true,opacity:.32,side:THREE.DoubleSide,roughness:.4});for(const s of[-1,1]){const wing=orb(mantis,[s*.18,1.74,-.9],[.27,.06,1.15],wingMat);wing.rotation.z=s*-.1;wing.rotation.y=s*-.07;bodies.push(wing)}mantis.rotation.y=.4;mantis.scale.setScalar(1.25);scene.add(mantis);
const preyGroup=new THREE.Group();scene.add(preyGroup);const bugs=[];const bugBody=new THREE.MeshStandardMaterial({color:'#9d7265',roughness:.55,emissive:'#422318',emissiveIntensity:.3});const bugWing=new THREE.MeshStandardMaterial({color:'#abbbc0',transparent:true,opacity:.5,side:THREE.DoubleSide});const bugEye=new THREE.MeshStandardMaterial({color:'#c48054',emissive:'#60331d',emissiveIntensity:.5});const bugLeg=new THREE.MeshStandardMaterial({color:'#697567'});
function makeBug(){const group=new THREE.Group(),body=new THREE.Mesh(new THREE.SphereGeometry(.17,8,6),bugBody);body.scale.set(1,.7,1.6);group.add(body);const h=new THREE.Mesh(new THREE.SphereGeometry(.11,8,6),bugEye);h.position.set(0,.02,.23);group.add(h);const wings=[];for(const s of[-1,1]){const w=new THREE.Mesh(new THREE.SphereGeometry(.19,8,4),bugWing);w.scale.set(1.6,.08,1);w.position.set(s*.23,.09,-.04);w.rotation.y=s*.4;group.add(w);wings.push(w);for(let i=0;i<3;i++)limb(group,[s*.1,-.02,.1-i*.12],[s*.32,-.15,.15-i*.15],.012,.004,bugLeg)}group.position.set((Math.random()-.5)*14,.3,(Math.random()-.5)*14);preyGroup.add(group);const b={group,wings,angle:Math.random()*Math.PI*2,phase:Math.random()*6,alive:true,respawn:0};bugs.push(b);return b}for(let i=0;i<12;i++)makeBug();
const targetRing=new THREE.Mesh(new THREE.RingGeometry(.45,.47,40),new THREE.MeshBasicMaterial({color:'#bd9060',transparent:true,opacity:.8,side:THREE.DoubleSide}));targetRing.rotation.x=-Math.PI/2;targetRing.position.y=.025;scene.add(targetRing);
const particleGeo=new THREE.BufferGeometry();const pCount=400;const pArray=new Float32Array(pCount*3),pColors=new Float32Array(pCount*3);const pData=Array.from({length:pCount},()=>({life:0,v:new THREE.Vector3()}));for(let i=0;i<pCount;i++)pArray[i*3+1]=-20;particleGeo.setAttribute('position',new THREE.BufferAttribute(pArray,3));particleGeo.setAttribute('color',new THREE.BufferAttribute(pColors,3));const particles=new THREE.Points(particleGeo,new THREE.PointsMaterial({size:.09,vertexColors:true,transparent:true,opacity:.9}));scene.add(particles);let pCursor=0;function burst(pos){const n=Math.round(18+state.chaos*.65);for(let j=0;j<n;j++){const i=pCursor++%pCount,p=pData[i];p.life=.6+Math.random()*.6;p.v.set((Math.random()-.5)*5,1+Math.random()*4,(Math.random()-.5)*5).multiplyScalar(1+state.chaos/80);pArray.set([pos.x,pos.y+.2,pos.z],i*3);const c=new THREE.Color(state.chaos>70?'#df744c':'#cedb72');pColors.set([c.r,c.g,c.b],i*3)}particleGeo.attributes.color.needsUpdate=true}
const slashMat=new THREE.MeshBasicMaterial({color:'#d9f18a',side:THREE.DoubleSide,transparent:true,opacity:0});const slash=new THREE.Mesh(new THREE.TorusGeometry(1.1,.023,4,36,Math.PI*1.35),slashMat);slash.rotation.x=.4;mantis.add(slash);slash.position.set(0,1.1,1.3);
let t=0,last=performance.now(),strike=0,cooldown=0,frames=0,fpsLast=last;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;function animate(now){requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;frames++;if(now-fpsLast>1000){$('fps').textContent=Math.round(frames*1000/(now-fpsLast))+' FPS';frames=0;fpsLast=now}controls.update();if(!state.paused){t+=dt;state.chaos=Math.max(8,state.chaos-dt*.55);const n=Math.min(24,12+Math.floor(state.chaos/8));if(bugs.length<n)makeBug();cooldown=Math.max(0,cooldown-dt);strike=Math.max(0,strike-dt*4);const visible=bugs.slice(0,n);let target=null,distance=Infinity;for(const b of bugs){b.group.visible=b.alive&&visible.includes(b);if(!b.alive){b.respawn-=dt;if(b.respawn<=0){b.alive=true;b.group.position.set((Math.random()-.5)*14,.3,(Math.random()-.5)*14)}continue}if(!visible.includes(b))continue;b.angle+=Math.sin(t*1.3+b.phase)*dt*1.4;const p=b.group.position;p.x+=Math.sin(b.angle)*dt*(.35+state.chaos*.01);p.z+=Math.cos(b.angle)*dt*(.35+state.chaos*.01);if(Math.hypot(p.x,p.z)>7.5)b.angle+=Math.PI*.9;p.x=clamp(p.x,-8,8);p.z=clamp(p.z,-8,8);p.y=.24+Math.sin(t*7+b.phase)*.06;b.group.rotation.y=b.angle;b.wings.forEach((w,i)=>w.rotation.z=Math.sin(t*32)*.2*(i?1:-1));const d=p.distanceTo(new THREE.Vector3(mantis.position.x,.3,mantis.position.z));if(d<distance){distance=d;target=b}}
if(target){const p=target.group.position;const dir=new THREE.Vector3(p.x-mantis.position.x,0,p.z-mantis.position.z);const yaw=Math.atan2(dir.x,dir.z);let delta=yaw-mantis.rotation.y;delta=Math.atan2(Math.sin(delta),Math.cos(delta));mantis.rotation.y+=delta*Math.min(1,dt*(2+state.chaos*.05));if(distance>1.45){mantis.position.addScaledVector(dir.normalize(),dt*(1.2+state.chaos*.04))}targetRing.position.set(p.x,.03,p.z);targetRing.visible=$('prey-layer').checked;const hunting=distance<1.65;const mode=strike>.1?'STRIKING':hunting?'LOCKED ON':'SEARCHING';$('behavior').textContent=mode;$('hunt-state').textContent=mode==='STRIKING'?'Striking':mode==='LOCKED ON'?'Locked on':'Searching';if(hunting&&cooldown===0){strike=1;cooldown=1.4/(1+state.chaos/28);target.alive=false;target.group.visible=false;target.respawn=1.5;state.kills++;burst(p);tone(120+state.chaos*3)}}
mantis.position.y=Math.sin(t*4)*.035;legs.forEach((leg,i)=>{leg.rotation.x=Math.sin(t*(5+state.chaos*.15)+i*Math.PI)*.1;leg.rotation.z=Math.cos(t*(5+state.chaos*.15)+i*Math.PI)*.07});arms.forEach((arm,i)=>{arm.rotation.x=-Math.sin(strike*Math.PI)*1.15;arm.rotation.z=(i?1:-1)*(.1+Math.sin(t*1.5)*.04+strike*.2)});head.rotation.y=Math.sin(t*1.4)*.17;slashMat.opacity=strike*.75;slashMat.color.set(state.chaos>70?'#ed9465':'#d9f18a');slash.rotation.z=t*3;for(let i=0;i<pCount;i++){const p=pData[i];if(p.life>0){p.life-=dt;p.v.y-=dt*5;pArray[i*3]+=p.v.x*dt;pArray[i*3+1]+=p.v.y*dt;pArray[i*3+2]+=p.v.z*dt;if(p.life<=0)pArray[i*3+1]=-20}}particleGeo.attributes.position.needsUpdate=true;
if(!reduced&&state.chaos>65&&strike>.6){camera.position.x+=(Math.random()-.5)*.028*(state.chaos/100);camera.position.y+=(Math.random()-.5)*.016}if(frames%12===0){updateTelemetry();$('targets-count').textContent=visible.filter(b=>b.alive).length;$('coordinates').textContent='X '+mantis.position.x.toFixed(1)+'  Y '+mantis.position.y.toFixed(1)+'  Z '+mantis.position.z.toFixed(1)}}renderer.render(scene,camera);drawRadar(t,mantis,bugs)}
requestAnimationFrame(animate);$('scene-loading').hidden=true;function toggleWire(){const enabled=$('wire-layer').checked;wires.forEach(w=>w.visible=enabled);$('wire-button').classList.toggle('active',enabled);$('wire-button').setAttribute('aria-pressed',String(enabled))}$('wire-layer').onchange=toggleWire;$('wire-button').onclick=()=>{$('wire-layer').checked=!$('wire-layer').checked;toggleWire()};$('body-layer').onchange=e=>bodies.forEach(b=>{b.material=b.material.clone();b.material.transparent=true;b.material.opacity=e.target.checked?.9:0});$('prey-layer').onchange=e=>{preyGroup.visible=e.target.checked;targetRing.visible=e.target.checked};$('home-camera').onclick=()=>{camera.position.set(9,7,11);controls.target.set(0,1,0);controls.update()};$('zoom-in').onclick=()=>{camera.position.lerp(controls.target,.15);controls.update()};$('zoom-out').onclick=()=>{camera.position.sub(controls.target).multiplyScalar(1.15).add(controls.target);controls.update()};$('rotate-camera').onclick=e=>{controls.autoRotate=!controls.autoRotate;e.currentTarget.classList.toggle('active',controls.autoRotate)};return{reset(){mantis.position.set(0,0,0);mantis.rotation.y=.4;cooldown=0;strike=0;for(const b of bugs){b.alive=true;b.group.position.set((Math.random()-.5)*14,.3,(Math.random()-.5)*14)}}}}
function drawRadar(t,mantis,bugs){const{ctx,w,h}=canvasContext('radar'),cx=w/2,cy=h/2,r=Math.min(w,h)*.4;ctx.strokeStyle='#244a32';ctx.lineWidth=.7;for(const f of[.33,.66,1]){ctx.beginPath();ctx.arc(cx,cy,r*f,0,Math.PI*2);ctx.stroke()}ctx.beginPath();ctx.moveTo(cx-r,cy);ctx.lineTo(cx+r,cy);ctx.moveTo(cx,cy-r);ctx.lineTo(cx,cy+r);ctx.stroke();const a=t*.7;const grad=ctx.createConicGradient(a,cx,cy);grad.addColorStop(0,'#94d87a35');grad.addColorStop(.13,'#94d87a00');grad.addColorStop(1,'#94d87a00');ctx.fillStyle=grad;ctx.beginPath();ctx.moveTo(cx,cy);ctx.arc(cx,cy,r,a,a+Math.PI*2);ctx.closePath();ctx.fill();for(const b of bugs){if(!b.alive||!b.group.visible||!$('prey-layer').checked)continue;ctx.fillStyle='#dc9f78';ctx.beginPath();ctx.arc(cx+b.group.position.x/9*r,cy+b.group.position.z/9*r,1.8,0,Math.PI*2);ctx.fill()}const mx=cx+mantis.position.x/9*r,my=cy+mantis.position.z/9*r;ctx.fillStyle='#d0f58a';ctx.beginPath();ctx.arc(mx,my,3,0,Math.PI*2);ctx.fill();ctx.strokeStyle='#c7ef77';ctx.beginPath();ctx.moveTo(mx,my);ctx.lineTo(mx+Math.sin(mantis.rotation.y)*10,my+Math.cos(mantis.rotation.y)*10);ctx.stroke()}
function pause(){state.paused=!state.paused;$('paused-overlay').hidden=!state.paused;$('pause').innerHTML=state.paused?'<span>▶</span> Resume simulation <kbd>SPACE</kbd>':'<span>Ⅱ</span> Pause simulation <kbd>SPACE</kbd>'}$('pause').onclick=pause;$('reset').onclick=()=>{world?.reset();state.kills=0;state.chaos=18;updateTelemetry()};$('expand').onclick=()=>$('viewer-panel').classList.toggle('expanded');document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT','SUMMARY','BUTTON'].includes(e.target.tagName))return;if(e.code==='Space'){e.preventDefault();pause()}if(e.key==='Escape')$('viewer-panel').classList.remove('expanded')});function navTo(id,button){document.querySelectorAll('.topbar nav button').forEach(b=>b.classList.toggle('nav-active',b.id===button));$(id).scrollIntoView({behavior:'smooth',block:'center'});$(id).classList.remove('attention');requestAnimationFrame(()=>$(id).classList.add('attention'))}$('battlefield-tab').onclick=()=>navTo('viewer-panel','battlefield-tab');$('specimen-tab').onclick=()=>navTo('specimen-panel','specimen-tab');$('activity-tab').onclick=()=>navTo('feed-panel','activity-tab');document.addEventListener('click',e=>{if(!$('token-dropdown').contains(e.target))$('token-dropdown').open=false});window.addEventListener('resize',drawChart);updateTelemetry();drawChart();let configLoading=false;
async function syncToken(){
  if(configLoading)return;configLoading=true;
  try{
    const response=await fetch('/api/config',{cache:'no-store'});const data=await response.json();
    if(!response.ok)throw Error(data.error||'Token settings unavailable.');
    $('owner-settings').hidden=!data.canEdit;
    $('public-mint').textContent=data.mint||'Waiting for the owner to add a CA.';
    const nextMint=data.mint||'';
    if(nextMint!==state.mint||state.mode==='loading'){if(nextMint)connectMint(nextMint);else enterDemo();}
  }catch(error){$('token-help').textContent=error.message;$('token-label').textContent=state.mint?state.mint.slice(0,6)+'…'+state.mint.slice(-4):'Token settings unavailable';}
  finally{configLoading=false;}
}
syncToken();setInterval(syncToken,10000);
